name: Generate ASCII artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Execute Cowsay CMD
              run: cowsay -f dog "Hello world" >> cowsay.txt

            - name: Sleep for 30 seconds
              run: sleep 30

    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10

            - name: Test file exists
              run: grep -i "cowsay" cowsay.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat cowsay.txt

            - name: Deploy
              run: echo Deploying ...
            