name: Generate ASCII artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Execute Cowsay CMD
              run: cowsay -f gnu "Hello cowsay" >> cowsay.txt

            - name: Upload Cowsay text file
              uses: actions/upload-artifact@v4
              with:
                name: cowsay-text-file
                path: cowsay.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Cowsay text file
              uses: actions/download-artifact@v5
              with:
                name: cowsay-text-file

            - name: Test file exists
              run: grep -i "cowsay" cowsay.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Download Cowsay text file
              uses: actions/download-artifact@v5
              with:
                name: cowsay-text-file

            - name: Read file
              run: cat cowsay.txt

            - name: Deploy
              run: echo Deploying ...
            