name: Exploring variables and secrets

on: 
    push

#variables
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: gabrielabalbuena
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              env: 
                DOCKER_PASSWORD: secure-password
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest